### ISSUE TITLE
fill up a tunnel 

### ISSUE THREAD

**Issue by skhaen** [miki151/keeperrl#805] opened 2016-07-28 12:01 UTC
Can't use the action "fill up a tunnel" on more than *one* case at the same time

```
CONFIG
Debian 8 (with systemd) and Cinnamon desktop
64 bits
KeeperRL alpha 19 (2016-07-26 7a18-dirty) from itch.io
keeper_lin64.sh
```

**Comment by miki151** [comment] 2016-09-06 10:19
It's by design to prevent closing-off areas.

**Closed by miki151** 2016-09-06 10:19 UTC
