### ISSUE TITLE
Having trouble compiling KeeperRL these days

### ISSUE THREAD

**Issue by keepermanj** [miki151/keeperrl#1249] opened 2018-09-26 19:54 UTC
My current error is as follows:

player_control.cpp: In member function 'std::__cxx11::string PlayerControl::getTriggerLabel(const AttackTrigger&) const':
player_control.cpp:629:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
player_control.cpp: At global scope:
player_control.cpp:505:36: warning: 'std::experimental::optional<std::pair<ViewId, int> > getCostObjWithZero(CostInfo)' defined but not used [-Wunused-function]
 static optional<pair<ViewId, int>> getCostObjWithZero(CostInfo cost) {
                                    ^~~~~~~~~~~~~~~~~~
g++ -MMD -Wall -std=c++1y -Wno-sign-compare -Wno-unused-variable -Wno-strict-aliasing -Wl,--stack,16000000 -I. -I./extern -Winvalid-pch -DWINDOWS -g -fno-omit-frame-pointer -O2 -c player.cpp -o obj/player.o
g++ -MMD -Wall -std=c++1y -Wno-sign-compare -Wno-unused-variable -Wno-strict-aliasing -Wl,--stack,16000000 -I. -I./extern -Winvalid-pch -DWINDOWS -g -fno-omit-frame-pointer -O2 -c opengl.cpp -o obj/opengl.o
In file included from C:/msys64/mingw32/i686-w64-mingw32/include/windows.h:71:0,
                 from C:/msys64/mingw32/include/SDL2/SDL_opengl.h:120,
                 from opengl.h:12,
                 from opengl.cpp:2:
color.h:64:16: error: expected unqualified-id before numeric constant
   static Color TRANSPARENT;
                ^
make[1]: *** [Makefile-win:92: obj/opengl.o] Error 1
make: *** [Makefile-win:84: all] Error 2

**Comment by miki151** [comment] 2018-09-26 20:11
Can you add this the following line at the beginning of color.h and see if there are any other errors?

#under TRANSPARENT

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by keepermanj** [comment] 2018-09-27 17:52
Next error follows this post

**Comment by keepermanj** [comment] 2018-09-27 17:53
g++ -MMD -Wall -std=c++1y -Wno-sign-compare -Wno-unused-variable -Wno-strict-aliasing -Wl,--stack,16000000 -I. -I./extern -Winvalid-pch -DWINDOWS -g -fno-omit-frame-pointer -O2 -c map_gui.cpp -o obj/map_gui.o
In file included from fx_manager.h:5:0,
                 from map_gui.cpp:37:
fx_particle_system.h:52:31: error: 'uint' has not been declared
   ParticleSystemId(int index, uint spawnTime) : index(index), spawnTime(spawnTime) {}
                               ^~~~
fx_particle_system.h:59:3: error: 'uint' does not name a type; did you mean 'rint'?
   uint getSpawnTime() const { return spawnTime; }
   ^~~~
   rint
fx_particle_system.h:63:3: error: 'uint' does not name a type; did you mean 'rint'?
   uint spawnTime;
   ^~~~
   rint
fx_particle_system.h: In constructor 'fx::ParticleSystemId::ParticleSystemId(int, int)':
fx_particle_system.h:52:63: error: class 'fx::ParticleSystemId' does not have any field named 'spawnTime'
   ParticleSystemId(int index, uint spawnTime) : index(index), spawnTime(spawnTime) {}
                                                               ^~~~~~~~~
fx_particle_system.h: At global scope:
fx_particle_system.h:74:3: error: 'uint' does not name a type; did you mean 'rint'?
   uint randomSeed;
   ^~~~
   rint
fx_particle_system.h:94:5: error: 'uint' does not name a type; did you mean 'rint'?
     uint randomSeed = 123;
     ^~~~
     rint
fx_particle_system.h:98:45: error: 'uint' has not been declared
   ParticleSystem(FXName, const InitConfig&, uint spawnTime, vector<SubSystem>);
                                             ^~~~
fx_particle_system.h:115:3: error: 'uint' does not name a type; did you mean 'rint'?
   uint spawnTime;
   ^~~~
   rint
fx_particle_system.h:144:3: error: 'uint' does not name a type; did you mean 'rint'?
   uint randomSeed();
   ^~~~
   rint
In file included from map_gui.cpp:37:0:
fx_manager.h:67:37: error: 'uint' has not been declared
   ParticleSystem makeSystem(FXName, uint spawnTime, InitConfig);
                                     ^~~~
fx_manager.h:84:3: error: 'uint' does not name a type; did you mean 'rint'?
   uint spawnClock = 1;
   ^~~~
   rint
In file included from C:/msys64/mingw32/i686-w64-mingw32/include/windows.h:71:0,
                 from C:/msys64/mingw32/include/SDL2/SDL_opengl.h:120,
                 from opengl.h:12,
                 from texture.h:19,
                 from renderer.h:24,
                 from gui_elem.h:20,
                 from map_gui.h:19,
                 from map_gui.cpp:18:
map_gui.cpp: In member function 'void MapGui::drawHealthBar(Renderer&, Vec2, Vec2, const ViewObject&)':
map_gui.cpp:543:65: error: expected unqualified-id before numeric constant
   renderer.drawFilledRectangle(fullRect.minusMargin(-1), Color::TRANSPARENT, Color::BLACK.transparency(100));
                                                                 ^
map_gui.cpp: In member function 'void MapGui::drawCreatureHighlight(Renderer&, Vec2, Vec2, Color)':
map_gui.cpp:1028:69: error: expected unqualified-id before numeric constant
     renderer.drawFilledRectangle(Rectangle(pos, pos + size), Color::TRANSPARENT, color);
                                                                     ^
map_gui.cpp: In member function 'void MapGui::drawSquareHighlight(Renderer&, Vec2, Vec2)':
map_gui.cpp:1035:69: error: expected unqualified-id before numeric constant
     renderer.drawFilledRectangle(Rectangle(pos, pos + size), Color::TRANSPARENT, Color::LIGHT_GRAY);
                                                                     ^
map_gui.cpp: In member function 'Color MapGui::getHighlightColor(const ViewIndex&, HighlightType)':
map_gui.cpp:156:1: warning: control reaches end of non-void function [-Wreturn-type]
 }

**Comment by nadult** [comment] 2018-10-01 18:59
What version of g++ are you using? It probably fails to compile, because it's a bit too old. I'll be back form a holiday on the 8th and I'll try fixing it so it will compile on the older versions as well.

**Comment by keepermanj** [comment] 2018-10-06 13:34
Thanks nadult,

typedef unsigned int uint;
^fixes fx_particle_system on my compiler

#undef TRANSPARENT also needed in map_gui.h
gui_builder.h .h   needs :       #undef TECHNOLOGY
gui_elem.h     needs:     #undef TRANSPARENT
I think I need to link against the correct library for glDebugMessageCallback@8
....nce_type.o -mwindows keeper32.res -lvorbisfile -lvorbis -logg -lSDL2_image -lkernel32 -luser32 -lgdi32 -lcomdlg32 -lole32 -ldinput -lddraw -ldxguid -lwinmm -ldsound -lpsapi -lgdiplus -lshlwapi -luuid -lSDL2 -lSDL2main  -lglut -lglu32 -lz -ljpeg -lopenal -lopengl32 -lcurl -limagehlp -l pthread
obj/opengl.o: In function Z25installOpenglDebugHandlerv':
C:\msys64\home\aj268\keeperrl/opengl.cpp:127: undefined reference to_imp__glDebugMessageCallback@8'...

**Comment by keepermanj** [comment] 2018-10-06 13:42
aj268@LAPTOP-U8FGA5EG MINGW32 ~
$ gcc --version
gcc.exe (Rev2, Built by MSYS2 project) 7.1.0

**Comment by keepermanj** [comment] 2018-10-06 13:47
$ g++ --version
g++.exe (Rev2, Built by MSYS2 project) 7.1.0

**Comment by nadult** [comment] 2018-10-08 10:02
The problem is not with gcc version but with mingw environment being a bit different from linux. Michał promised to fix those issues in the next test release.

**Comment by miki151** [comment] 2018-10-18 21:17
These errors should be fixed now.

**Closed by miki151** 2018-10-18 21:17 UTC
